//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string BookPublication { get; set; }
        public Nullable<System.DateTime> BookPublicTime { get; set; }
        public Nullable<double> BookPrice { get; set; }
        public string BookISBN { get; set; }
        public string BookTitle { get; set; }
        public string BookImage { get; set; }
        public string BookAuthor { get; set; }
        public string BookTranslator { get; set; }
        public string BookIntroduce { get; set; }
        public string BookClassfication { get; set; }
    }
}
