//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string BookName { get; set; }
        public string BookIntroduce { get; set; }
        public string BookISBN { get; set; }
        public Nullable<double> BookPrice { get; set; }
        public Nullable<int> BookAmount { get; set; }
        public Nullable<double> BookTotalPrice { get; set; }
    }
}
