//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string QQ { get; set; }
        public int Type { get; set; }
        public string ClientIP { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string HeadPic { get; set; }
    }
}
